# Generated by Django 2.2.7 on 2019-11-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191126_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='definite_transportation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Carpool', 'Carpool would be necessary')], default='No', max_length=50),
        ),
    ]
