# Generated by Django 2.2.7 on 2019-11-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camper',
            name='no_scholarship',
        ),
        migrations.RemoveField(
            model_name='camper',
            name='scholarship_granted',
        ),
        migrations.AddField(
            model_name='camper',
            name='if_scholarship_not_granted',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='camper',
            name='currently_involved_activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='camper',
            name='definite_transportation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Carpool', 'Carpool would be necessary')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='like_to_change',
            field=models.CharField(max_length=255),
        ),
    ]
