# Generated by Django 2.2.7 on 2019-11-20 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previously_attended', models.BooleanField()),
                ('legal_full_name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(max_length=255)),
                ('preferred_pronouns', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('name_of_school', models.CharField(max_length=255)),
                ('how_heard_about', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('gain_from_camp', models.CharField(max_length=255)),
                ('dietary_restrictions', models.CharField(max_length=255)),
                ('tshirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', '2XL'), ('XXXL', '3XL')], max_length=5)),
                ('verify_sensitive_topics', models.BooleanField()),
                ('accomodations', models.CharField(blank=True, max_length=255)),
                ('sponsor_org', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_camp', models.CharField(max_length=255)),
                ('street_address_location', models.CharField(max_length=255)),
                ('city_location', models.CharField(max_length=255)),
                ('time_of_arrival', models.CharField(max_length=255)),
                ('time_of_departure', models.CharField(max_length=255)),
                ('meeting_place_for_carpool', models.CharField(max_length=255)),
                ('camper', models.ManyToManyField(to='core.Camper')),
            ],
        ),
    ]
