# Generated by Django 2.2.7 on 2019-11-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191126_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='have_disability',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
