# Generated by Django 2.2.7 on 2019-11-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='camper',
            new_name='campers',
        ),
    ]
