# Generated by Django 2.2.7 on 2019-11-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191120_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='campers',
            field=models.ManyToManyField(through='core.Registration', to='core.Camper'),
        ),
    ]
