# Generated by Django 2.2.7 on 2019-12-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191130_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinformation',
            name='legal_full_name_of_camper',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
