# Generated by Django 2.2.7 on 2019-11-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191122_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='previously_attended',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
