# Generated by Django 2.2.7 on 2019-12-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191130_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinformation',
            name='camper_signed_for_the_entire_form',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='date_of_camper_signed_for_the_entire_form',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='date_of_guardian_signed_for_the_entire_form',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='guardian_signed_for_the_entire_form',
        ),
    ]
