# Generated by Django 2.2.7 on 2019-12-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191203_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinformation',
            name='camper_consent_for_community_values_agreement',
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='explain_any_other_unlisted_medical_history',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='provide_explanation_for_any_checked_mental_illness_items',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
