# Generated by Django 2.2.7 on 2019-12-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191203_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinformation',
            name='camper_consent_for_waiver_to_participate',
        ),
    ]
