# Generated by Django 2.2.7 on 2019-12-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_medicalinformation_camper_consent_for_waiver_to_participate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinformation',
            name='camper_dietary_preference_choices',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Dairy-free', 'Dairy-free'), ('Nut-free', 'Nut-free'), ('Gluten-free', 'Gluten-free')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='camper_mental_health_history_choices',
            field=models.CharField(blank=True, choices=[('any_eating_disorders', 'any_eating_disorders'), ('add_or_adhd', 'add_or_adhd'), ('any_audio_visual_hallucinations', 'any_audio_visual_hallucinations'), ('ptsd', 'ptsd'), ('gender_dysphoria', 'gender_dysphoria'), ('any_significant_life_event_that_continues_to_affect_camper', 'any_significant_life_event_that_continues_to_affect_camper'), ('any_sexual_assault_or_sexual_violence', 'any_sexual_assault_or_sexual_violence'), ('depression', 'depression'), ('obsessive_compulsive_disorder', 'obsessive_compulsive_disorder'), ('any_panic_attacks', 'any_panic_attacks'), ('anxiety', 'anxiety'), ('any_mental_or_verbal_abuse', 'any_mental_or_verbal_abuse'), ('any_physical_abuse', 'any_physical_abuse'), ('any_trouble_sleeping_or_sleep_disorders', 'any_trouble_sleeping_or_sleep_disorders')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='camper_physical_health_history_choices',
            field=models.CharField(blank=True, choices=[('recent_injury_,_illness_or_infectious_disease', 'recent_injury_,_illness_or_infectious_disease'), ('chronic_or_recurring_illness', 'chronic_or_recurring_illness'), ('asthma', 'asthma'), ('dysmenorrhea', 'dysmenorrhea'), ('frequent_ear_infections', 'frequent_ear_infections'), ('seizure_disorders_or_convulsions', 'seizure_disorders_or_convulsions'), ('dizziness_during_or_after_exercise', 'dizziness_during_or_after_exercise'), ('chest_pain_during_or_after_exercise', 'chest_pain_during_or_after_exercise'), ('heart_defect_/_disease', 'heart_defect_/_disease'), ('hypertension', 'hypertension'), ('bleeding_/_clotting_disorder', 'bleeding_/_clotting_disorder'), ('diabetes', 'diabetes'), ('mononucleosis_(_in_last_12_months_)', 'mononucleosis_(_in_last_12_months_)'), ('chicken_pox', 'chicken_pox'), ('measles', 'measles'), ('german_measles', 'german_measles'), ('mumps', 'mumps'), ('tuberculosis', 'tuberculosis'), ('hepatitis', 'hepatitis'), ('joint_problems', 'joint_problems'), ('fractures', 'fractures'), ('frequent_headaches', 'frequent_headaches'), ('head_injury', 'head_injury'), ('eating_disorder', 'eating_disorder'), ('diarrhea_or_constipation', 'diarrhea_or_constipation'), ('frequent_stomach_aches', 'frequent_stomach_aches'), ('wearing_glasses_or_contacts', 'wearing_glasses_or_contacts'), ('surgery_or_being_hospitalized', 'surgery_or_being_hospitalized'), ('wearing_medic_alert_id', 'wearing_medic_alert_id'), ('other_unlisted_medical_history', 'other_unlisted_medical_history')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='can_camper_be_picked_up_by_guardian_or_emergency_contact',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=[], max_length=255),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='emergency_home_work_cell',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Cell', 'Cell')], default=[], max_length=255),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='first_guardian_home_work_or_cell',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Cell', 'Cell')], default=[], max_length=255),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='guardian_authorized_over_counter_medications_choices',
            field=models.CharField(blank=True, choices=[('acetaminophen', 'acetaminophen'), ('ibuprofen', 'ibuprofen'), ('diphenhydramine', 'diphenhydramine'), ('bismuth_subsalicylate', 'bismuth_subsalicylate'), ('calcium_carbonate', 'calcium_carbonate'), ('polyethylene_glycol', 'polyethylene_glycol'), ('bacitracin', 'bacitracin'), ('I_consent_for_all_of_the_above', 'I_consent_for_all_of_the_above'), ('I_do_not_want_any_over_the_counter_medications_to_be_given', 'I_do_not_want_any_over_the_counter_medications_to_be_given')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='second_guardian_home_work_or_cell',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Cell', 'Cell')], default=[], max_length=255),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='third_guardian_home_work_or_cell',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Cell', 'Cell')], default=[], max_length=255),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='was_tuberculin_test_positive_or_negative',
            field=models.CharField(choices=[('Yes, it was Positive', 'Yes, it was Positive'), ('No, it was Negative', 'No, it was Negative')], default=[], max_length=255),
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='will_camper_take_medication_while_at_camp',
            field=models.CharField(default=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='camper',
            name='any_additional_accommodations_needed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='does_camper_have_any_dietary_restrictions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='does_the_camper_have_any_disabilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='does_the_camper_have_any_sponsoring_organizations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='does_the_camper_have_other_companies_paying',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
