# Generated by Django 2.2.7 on 2019-12-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191204_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinformation',
            name='guardian_consent_for_community_values_agreement',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='guardian_consent_for_waiver_to_participate',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='guardian_consent_to_freedom_of_expression_consent',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='guardian_consent_to_health_information_and_treatment_at_ASPYRE',
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='camper_mental_health_history_choices',
            field=models.CharField(blank=True, choices=[('any_eating_disorders', 'any_eating_disorders'), ('add_or_adhd', 'add_or_adhd'), ('any_audio_visual_hallucinations', 'any_audio_visual_hallucinations'), ('ptsd', 'ptsd'), ('gender_dysphoria', 'gender_dysphoria'), ('any_significant_life_event_that_continues_to_affect_camper', 'any_significant_life_event_that_continues_to_affect_camper'), ('any_sexual_assault_or_sexual_violence', 'any_sexual_assault_or_sexual_violence'), ('depression', 'depression'), ('obsessive_compulsive_disorder', 'obsessive_compulsive_disorder'), ('any_panic_attacks', 'any_panic_attacks'), ('anxiety', 'anxiety'), ('any_mental_or_verbal_abuse', 'any_mental_or_verbal_abuse'), ('any_physical_abuse', 'any_physical_abuse'), ('any_trouble_sleeping_or_sleep_disorders', 'any_trouble_sleeping_or_sleep_disorders'), ('any_other_unlisted_mental_illness', 'any_other_unlisted_mental_illness')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='does_camper_have_any_food_allergies',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='guardian_or_18yr_old_consent_to_photo_release',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
