# Generated by Django 2.2.7 on 2019-12-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191204_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camper',
            name='would_the_camper_like_to_be_added_facebook',
        ),
    ]
