# Generated by Django 2.2.7 on 2019-12-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_camper_would_the_camper_like_to_be_added_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinformation',
            name='third_guardian_home_work_or_cell',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='third_guardian_name',
        ),
        migrations.RemoveField(
            model_name='medicalinformation',
            name='third_guardian_phone_number',
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='any_physical_activities_to_be_limited_or_restricted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
